### ISSUE TITLE
getIpByHost请求时间太久

### ISSUE THREAD

**Issue by liuyuanming** [aliyun/alicloud-ios-demo#104]
平台：iOS
问题： getIpByHost请求时间太久（8s以上），有没有办法控制或者是里边有什么样的机制
重现：把手机wifi设置一个网络不通的ip代理，发现上述方法请求时间过长。

**Comment by homelesser** [comment]
使用上我们更建议使用异步接口getIpByHostAsync。
[如何利用HTTPDNS降低DNS解析开销](https://help.aliyun.com/document_detail/30144.html?spm=5176.doc30140.6.130.TkDh21)

**Comment by liuyuanming** [comment]
好的。谢谢。
