### ISSUE TITLE
用pod的方式需要怎么配置ipv6

### ISSUE THREAD

**Issue by sunzeboy** [aliyun/alicloud-ios-demo#111]
兼容IPv6-Only网络

OSS移动端SDK为了解决无线网络下域名解析容易遭到劫持的问题，已经引入了HTTPDNS进行域名解析，直接使用IP请求OSS服务端。在IPv6-Only的网络下，可能会遇到兼容性问题。而APP官方近期发布了关于IPv6-only网络环境兼容的APP审核要求，为此，SDK从2.5.0版本开始已经做了兼容性处理。在新版本中，除了-ObjC的设置，还需要引入两个系统库：

libresolv.tbd
SystemConfiguration.framework

以上这些应该是手动引入framwork需要配置的吧，用pod的方式也得进行-ObjC的设置和引入两个系统库吗？

Start resolved network to see if in IPv6-Only env
[-[OSSIPv6Adapter isIPv6OnlyNetwork]]: Not IPv6-Only network now
[-[OSSIPv6Adapter appDidBecomeActiveFunc]]: App become active, refresh IPv6-Only status.

**Comment by xuyecan** [comment]
只需要在`other linker flags`中加上`-ObjC`就可以了。库的引入已经在podspec中设置。
