### ISSUE TITLE
请问有WKWebView版本吗？

### ISSUE THREAD

**Issue by hardyZhi** [aliyun/alicloud-ios-demo#126]
请问有WKWebView版本吗？在WKWebView下怎么使用？

**Comment by SducodeMonkey** [comment]
WKWebView不支持NSURLProtocol拦截的。

**Comment by hardyZhi** [comment]
那么WKWebView就没办法支持HttpDNS了吗？

**Comment by SducodeMonkey** [comment]
基于目前苹果放出的WKWebView无法进行NSURLProtocol拦截，需要基于UIWebView来实现；
如果有强烈使用WKWebView的需求，可以搜索下“让WKWebView 支持 NSURLProtocol”，调用私有API实现并绕过审核，但是不建议这么做。
