### ISSUE TITLE
duplicate symbol

### ISSUE THREAD

**Issue by hornet1990** [aliyun/alicloud-ios-demo#130]
<img width="553" alt="duplicate" src="https://cloud.githubusercontent.com/assets/12495062/20995297/06eee60c-bd31-11e6-9606-d94ee1b02942.png">

**Comment by hornet1990** [comment]
https://help.aliyun.com/knowledge_detail/44399.html?spm=5176.7841952.2.7.fbCHKk

**Comment by SducodeMonkey** [comment]
参照你贴的链接，下载剥离UTDID的支付宝SDK。
