### ISSUE TITLE
和 sharesdk 一起使用就各种 bug 出现了,基本是不能正常使用的节奏

### ISSUE THREAD

**Issue by tpctt** [aliyun/alicloud-ios-demo#133]
步骤
1. 集成 aliyun , sharesdk
2. 初始化 sharesdk 和 aliyun
3. 做带 DNS 的网络访问

结果:
不能正常得到数据,DEBUG 各种错误都有

**Comment by SducodeMonkey** [comment]
提供下具体的错误信息？有没有保存Log？

**Comment by iOS-Misaki** [comment]
AliMobileAnalytics/UTDID.framework/UTDID(AidManager.o)' does not contain bitcode ？
引入的UTDID 不支持bitcode 么 有没有支持bitcode的版本

**Comment by SducodeMonkey** [comment]
@iOS-Misaki 支持bitcode的，去控制台下载最新版本SDK。
