### ISSUE TITLE
在集成aliyun_oss 和阿里移动数据分析后，导致ipa的体积飙升。这个怎么解决

### ISSUE THREAD

**Issue by iOS-Misaki** [aliyun/alicloud-ios-demo#151]
在集成aliyun_oss 和阿里移动数据分析后，导致ipa的体积飙升。这个怎么解决

**Comment by SducodeMonkey** [comment]
- 当前各SDK已比较精简，暂没有进一步缩减SDK体积的计划；
- 附：OSS为开源SDK，如发现可优化点可提issue。
