### ISSUE TITLE
iOS中怎么能简单判断自己被DNS劫持了？

### ISSUE THREAD

**Issue by hardyZhi** [aliyun/alicloud-ios-demo#152]
iOS 中怎么能简单判断自己是被DNS劫持了？我想先判断自己被劫持了，然后再走HttpDNS，没被劫持就不做任何改动，这样对程序影响最小。

**Comment by SducodeMonkey** [comment]
1. 仅靠客户端做劫持判断没有便捷的方式且不可行，例如解析域名A时，要提前清楚正确的域名解析结果列表（如果已经有该列表，为什么还要做域名解析？），localDNS解析结果做比较，若解析结果在列表中，说明没有被劫持，反之被劫持。
2. 如果已知App有域名劫持的现象，接入HTTPDNS服务即可，客户端做域名劫持实时分析没有必要的。

**Comment by hardyZhi** [comment]
好的，谢谢
