### ISSUE TITLE
httpdns 的缓存过期时间是多长?

### ISSUE THREAD

**Issue by czb1n** [aliyun/alicloud-ios-demo#161]
/**
 * 异步解析接口，首先查询缓存，若存在则返回结果，若不存在返回nil并且进行异步域名解析更新缓存
 *
 * @param host 域名(如www.aliyun.com)
 * @return 域名对应的解析结果
 */
 - (NSString *)getIpByHostAsync:(NSString *)host;

这里指的缓存的过期时间是多长?

**Comment by SducodeMonkey** [comment]
缓存过期时间和TTL时间保持一致的。
