### ISSUE TITLE
请问AlicloudHTTPDNS更新日志在哪里查看？

### ISSUE THREAD

**Issue by jaybowong** [aliyun/alicloud-ios-demo#173]
我们APP里AlicloudHTTPDNS的版本是v1.4.2，现在准备升级到最新1.5.1，但是没有找到更新日志。
在[官网](https://www.aliyun.com/product/httpdns?spm=5176.8142029.388261.87.WDYRC6
)也没找到更新日志的入口。

更新日志对于所有的APP开发者都非常重要，更新SDK前看一眼更新日志更靠谱。

如果有更新日志，希望能有一个**明显的入口**。

**Comment by SducodeMonkey** [comment]
阿里云控制台是SDK官方下载处，changeLog在下载页面都有列出。
附：https://mhub.console.aliyun.com/#/download
