### ISSUE TITLE
httpdns_ios_demo ipv6环境下没有请求到ip

### ISSUE THREAD

**Issue by NanNanCHN** [aliyun/alicloud-ios-demo#188]
httpdns_ios_demo ipv6环境下没有请求到ip,什么情况..

**Comment by SducodeMonkey** [comment]
HTTPDNS iOS SDK支持标准的IPv6网络环境自动适配，可参考[苹果官网文档](https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1)进行IPv6-Only网络环境搭建。
