### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by RtzX** [aliyun/alicloud-ios-demo#200]
看提交记录 版本是 1.9.2 
下载之后,看代码里面写的版本是 1.9.4 
到底什么版本啊?? 
 官网上也没有明确说明 . 目前最新版本是多少..

**Comment by SducodeMonkey** [comment]
- SDK版本号和ChangeLog可在移动云SDK下载控制台查看：https://mhub.console.aliyun.com/#/download
- 也可在移动云CocoaPods仓库查看：https://github.com/aliyun/aliyun-specs
