### ISSUE TITLE
Xcode 9 警告

### ISSUE THREAD

**Issue by iOS-Misaki** [aliyun/alicloud-ios-demo#210]
ManIOSDemo.m: runtime: UI API called from background thread: -[UIApplication delegate] must be 
ManIOSDemo.m:的pageHit方法中获取appDelegate必须要在主线程中获取
AppDelegate * appDelegate = (AppDelegate *)[UIApplication sharedApplication].delegate;
-[UIApplication delegate] must be used from main thread only

**Comment by SducodeMonkey** [comment]
该问题已修复。
