### ISSUE TITLE
示例代码去哪里找，demo里面没有找到啊

### ISSUE THREAD

**Issue by stevelyc** [aliyun/alicloud-ios-demo#241]
我clone httpdns_ios_demo之后，没有找到介绍里面说的示例代码。请问是哪里的问题

**Comment by duanhjlt** [comment]
你可以参考一下commitId：40b236dd，我看原来是有这些代码的，之后就删掉了

**Comment by stevelyc** [comment]
嗯嗯  已经找到了  有好多好东西可以参考
