### ISSUE TITLE
Main Thread Checker: UI API called on a background thread

### ISSUE THREAD

**Issue by SummerHF** [aliyun/alicloud-ios-demo#252]
## 强烈建议大家不要使用此框架, 同时我建议你们fire掉写这个SDK的人，可以肯定这个人极其没有责任心.
* 首先自定义的线程不起名字，难以调试, 定位问题，这是基本常识.
* 其次连我这种菜鸡都知道不能在异步线程hook App 的state, 而你们的SDK却出现这种低级错误. 每次App前后台切换的时候都会emit Main Thread Checker, 同时整个界面卡顿3, 到 4s钟, 体验极差. 
*  因为项目中用到了好几个阿里系的SDK，包括AliyunPlayerSDK，AliyunVodPlayerSDK， AliyunOSSiOS, AlicloudPush, 所以导致定位极其困难(因为报错的这几个函数你根本看不出是那个框架在用). 

```
UI API called on a background thread: -[UIApplication applicationState]
-[UTSelfStaticsManager getAppState] + 60
-[UTSelfStaticsManager onEventForCrash] + 256
__40-[UTMCSystemHook appDIdEnterBackground:]_block_invoke.51 + 196
_dispatch_call_block_and_release + 24
_dispatch_client_callout + 16
_dispatch_queue_override_invoke + 888
_dispatch_root_queue_drain + 376
_dispatch_worker_thread2 + 156
_pthread_wqthread + 472
```

![](http://ww4.sinaimg.cn/large/006tNc79ly1g59n5msr5kj30a70bd0ys.jpg)

> 你们不想写可以滚啊，何必写了坑别人咧!!!!!!!!!!!!!!! 而且反应了问题也无人答复，要不是公司指定，早就换了！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by wlwinston** [comment]
准备放弃了，日志里全是这类错误。调试模式下会非常卡

**Comment by skyinemas** [comment]
此问题已在AlicloudUT 5.2.0.8版本中修复，有2个升级方法：
1、请执行pod update并在Podfile.lock查看AlicloudUT版本是否为5.2.0.8
2、下载[压缩包](https://ios-repo.oss-cn-shanghai.aliyuncs.com/ut/5.2.0.8/ut.zip),解压得到UTMini.framework，替换同名库

**Comment by Zorodon** [comment]
我项目就用一个反馈的功能，这个问题卡主我好几天，找了半天特么才找到这里，好气！！
