### ISSUE TITLE
集成AlicloudMAN后与AlipaySDK-iOS冲突

### ISSUE THREAD

**Issue by spirit-jsb** [aliyun/alicloud-ios-demo#253]
使用 Cocoapods 集成 AlicloudMAN 后与 AlipaySDK-iOS 冲突，编译报错，错误信息为：

duplicate symbol _OBJC_CLASS_$_UTDIDAES in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDAES.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDAES in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDAES.o)
duplicate symbol _OBJC_CLASS_$_UTDIDBaseUtils in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDBaseUtils.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDBaseUtils in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDBaseUtils.o)
duplicate symbol _OBJC_CLASS_$_AidRequester in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(AidRequester.o)
duplicate symbol _OBJC_METACLASS_$_AidRequester in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(AidRequester.o)
duplicate symbol _OBJC_CLASS_$_AidManager in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(AidManager.o)
duplicate symbol _OBJC_METACLASS_$_AidManager in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(AidManager.o)
duplicate symbol _OBJC_CLASS_$_UTDIDIntUtils in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDIntUtils.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDIntUtils in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDIntUtils.o)
duplicate symbol _OBJC_CLASS_$_UTDIDStringUtils in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDStringUtils.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDStringUtils in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDStringUtils.o)
duplicate symbol _OBJC_CLASS_$_UTDIDTypeConvert in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDTypeConvert.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDTypeConvert in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDTypeConvert.o)
duplicate symbol _OBJC_CLASS_$_UTDIDMain in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDMain.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDMain in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDMain.o)
duplicate symbol _OBJC_CLASS_$_UTDIDOpenUDID in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDOpenUDID.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDOpenUDID in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDOpenUDID.o)
duplicate symbol _OBJC_CLASS_$_UTDIDHelper in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDHelper.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDHelper in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDHelper.o)
duplicate symbol _OBJC_CLASS_$_AidStorage in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(AidStorage.o)
duplicate symbol _OBJC_METACLASS_$_AidStorage in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(AidStorage.o)
duplicate symbol _OBJC_CLASS_$_UTDevice in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDevice.o)
duplicate symbol _OBJC_METACLASS_$_UTDevice in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDevice.o)
duplicate symbol _OBJC_IVAR_$_UTDIDKeychainItemWrapper.genericPasswordQuery in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDKeychainItemWrapper.o)
duplicate symbol _OBJC_CLASS_$_UTDIDKeychainItemWrapper in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDKeychainItemWrapper.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDKeychainItemWrapper in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDKeychainItemWrapper.o)
duplicate symbol _OBJC_IVAR_$_UTDIDKeychainItemWrapper.keychainItemData in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDKeychainItemWrapper.o)
duplicate symbol _OBJC_CLASS_$_UTDIDPersistentConf in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDPersistentConf.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDPersistentConf in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDPersistentConf.o)
duplicate symbol _OBJC_CLASS_$_UTDIDPersistentFile in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDPersistentFile.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDPersistentFile in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDPersistentFile.o)
duplicate symbol _OBJC_CLASS_$_UTDIDGTMBase64 in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDGTMBase64.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDGTMBase64 in:
    /Users/max/Code/BaokuChina/falcon/Pods/AlipaySDK-iOS/AlipaySDK.framework/AlipaySDK
    /Users/max/Code/BaokuChina/falcon/Pods/AlicloudUTDID/utdid/UTDID.framework/UTDID(UTDIDGTMBase64.o)
ld: 34 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

请尽快排查。

**Comment by skyinemas** [comment]
可下载并集成 [剥离UTDID的支付宝SDK](https://docs.open.alipay.com/54/104509)，保留阿里云平台的UTDID包。

具体参考此  [阿里云-移动云产品SDKUTDID冲突解决方案](https://help.aliyun.com/knowledge_detail/70257.html)

**Comment by spirit-jsb** [comment]
感谢🙏
