### ISSUE TITLE
Xcode11.0编译崩溃-HTTPDNS

### ISSUE THREAD

**Issue by TouchLiang** [aliyun/alicloud-ios-demo#256]
我的是swift项目，在Xcode11.0中多次执行HttpDnsService.sharedInstance()?.getIpByHostAsync(sourceURL.host!)后就会崩溃，线程崩溃，查不到具体原因。

**Comment by SducodeMonkey** [comment]
sdk版本？是否有堆栈日志提供下？

发自我的iPhone

**Comment by TouchLiang** [comment]
控制台log：libc++abi.dylib: terminating with uncaught exception of type NSException
其他log：
------------------------**************---------------------------
libsystem_pthread.dylib`_pthread_start:
    0x1c1504174 <+0>:   stp    x20, x19, [sp, #-0x20]!
    0x1c1504178 <+4>:   stp    x29, x30, [sp, #0x10]
    0x1c150417c <+8>:   add    x29, sp, #0x10            ; =0x10 
    0x1c1504180 <+12>:  tbnz   w5, #0x1d, 0x1c1504190    ; <+28>
    0x1c1504184 <+16>:  tbnz   w5, #0x1c, 0x1c1504198    ; <+36>
    0x1c1504188 <+20>:  mov    x0, x5
    0x1c150418c <+24>:  bl     0x1c1507d10               ; _pthread_start.cold.1
    0x1c1504190 <+28>:  mov    x0, x5
    0x1c1504194 <+32>:  bl     0x1c1507d64               ; _pthread_start.cold.4
    0x1c1504198 <+36>:  mov    x19, x0
    0x1c150419c <+40>:  bl     0x1c150817c               ; symbol stub for: ___chkstk_darwin
    0x1c15041a0 <+44>:  bl     0x1c15e0858               ; __thread_selfid
    0x1c15041a4 <+48>:  str    x0, [x19, #0xd8]
    0x1c15041a8 <+52>:  cmn    x0, #0x1                  ; =0x1 
    0x1c15041ac <+56>:  b.ne   0x1c15041b4               ; <+64>
    0x1c15041b0 <+60>:  bl     0x1c1507d38               ; _pthread_start.cold.2
    0x1c15041b4 <+64>:  ldr    x0, [x19, #0xf8]
    0x1c15041b8 <+68>:  cmp    w0, #0x0                  ; =0x0 
    0x1c15041bc <+72>:  cset   w8, ne
    0x1c15041c0 <+76>:  cmn    w0, #0x1                  ; =0x1 
    0x1c15041c4 <+80>:  cset   w9, ne
    0x1c15041c8 <+84>:  cmp    w9, w8
    0x1c15041cc <+88>:  b.eq   0x1c15041d4               ; <+96>
    0x1c15041d0 <+92>:  bl     0x1c1507d3c               ; _pthread_start.cold.3
    0x1c15041d4 <+96>:  adrp   x8, 280220
    0x1c15041d8 <+100>: ldr    x8, [x8, #0x1a8]
    0x1c15041dc <+104>: cbz    x8, 0x1c15041e8           ; <+116>
    0x1c15041e0 <+108>: mov    x0, x19
    0x1c15041e4 <+112>: bl     0x1c1505b70               ; _pthread_introspection_hook_callout_thread_start
    0x1c15041e8 <+116>: ldp    x8, x0, [x19, #0x90]
    0x1c15041ec <+120>: blr    x8
->  0x1c15041f0 <+124>: mov    x1, x0
    0x1c15041f4 <+128>: mov    x0, x19
    0x1c15041f8 <+132>: bl     0x1c15041fc               ; _pthread_exit
------------------------**************---------------------------
libsystem_kernel.dylib`__pthread_kill:
    0x1c15dfeb4 <+0>:  mov    x16, #0x148
    0x1c15dfeb8 <+4>:  svc    #0x80
->  0x1c15dfebc <+8>:  b.lo   0x1c15dfed8               ; <+36>
    0x1c15dfec0 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1c15dfec4 <+16>: mov    x29, sp
    0x1c15dfec8 <+20>: bl     0x1c15bef24               ; cerror_nocancel
    0x1c15dfecc <+24>: mov    sp, x29
    0x1c15dfed0 <+28>: ldp    x29, x30, [sp], #0x10
    0x1c15dfed4 <+32>: ret    
    0x1c15dfed8 <+36>: ret

**Comment by SducodeMonkey** [comment]
- 这个堆栈基本不可读，是否有格式化后的堆栈信息？
- 确认下 SDK 版本，SDK 目前最新版本是：1.17.3，可使用 Pod 集成 或者 到 https://emas.console.aliyun.com/#/sdkDownload 下载后手动集成。

**Comment by TouchLiang** [comment]
格式化后的堆栈信息目前无法查到，下载了新版SDK，还是崩溃，只是初始化，也会导致崩溃。也只在Xcode11 会出现这种情况。

**Comment by TouchLiang** [comment]
已解决。方法：更新到最新版SDK。
