### ISSUE TITLE
关于 IPV6 的问题。

### ISSUE THREAD

**Issue by ChangLiuXYZ** [aliyun/alicloud-ios-demo#71]
由于苹果要求 APP 必须支持 IPV6，所以我有几个疑问：
1. 服务 URL：http://203.107.1.1/{account_id}/d，现在直接这样访问貌似不行了吧；
2. 请求回来的 ip，直接放在 URL 使用也是不行的吧；
请问如何解决？

**Comment by lingmingyb** [comment]
https://yq.aliyun.com/articles/51118
请参考上述说明。
