### ISSUE TITLE
上传图片报IPV6警告，然后就卡住不走了

### ISSUE THREAD

**Issue by jashion** [aliyun/alicloud-ios-demo#72]
Start resolved network to see if in IPv6-Only env.
[-[OSSIPv6Adapter isIPv6OnlyNetwork]]: Not IPv6-Only network now.
[AlicloudReachabilityManager]: Network changed, Pre network status is not IPv6-Only.

**Comment by xuyecan** [comment]
请问做了如下设置了吗？  https://github.com/aliyun/aliyun-oss-ios-sdk#兼容ipv6-only网络

**Comment by jashion** [comment]
这个问题解决了，这个警告只是打印出来的日记，并没有阻塞主线程，是项目别的地方代码阻塞了主线程，不好意思。
